FROM base

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update && apt-get install unzip 

# LLVM/Clang

RUN apt-get -y install clang-10 lldb-10 lld-10

#Std Lib

RUN apt-get -y install libc++-10-dev libc++abi-10-dev

# GDB 

RUN apt-get -y install gdb

#Cmake 

COPY external-deps/cmake-3.18.1-Linux-x86_64.tar.gz .
RUN tar -xvf cmake-3.18.1-Linux-x86_64.tar.gz && rm cmake-3.18.1-Linux-x86_64.tar.gz && \
    cp -r cmake**/bin/* /usr/local/bin/ && cp -r cmake**/man/* /usr/local/man/ && \
    cp -r cmake**/share/* /usr/local/share/ && rm -rf cmake*

#  Minimalistic image library
COPY external-deps/CImg_latest.zip .
RUN unzip CImg_latest.zip && cp CImg-2.9.2_pre072920/CImg.h /usr/local/include && \
    rm -rf CImg*
