FROM base

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update

# wget
RUN apt-get install wget

# unzip
RUN apt-get install unzip 

#Git
RUn apt-get install -y  git-all

# GDB 
RUN apt-get -y install gdb

# LLVM/Clang
RUN apt install -y lsb-release wget software-properties-common
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
RUN ./llvm.sh && rm ./llvm.sh

#Cmake
COPY external-deps/cmake-3.18.1-Linux-x86_64.tar.gz .
RUN tar -xvf cmake-3.18.1-Linux-x86_64.tar.gz && rm cmake-3.18.1-Linux-x86_64.tar.gz && \
    cp -r cmake**/bin/* /usr/local/bin/ && cp -r cmake**/man/* /usr/local/man/ && \
    cp -r cmake**/share/* /usr/local/share/ && rm -rf cmake*

# Set Clang as the default compiler, cmake can take it from here
RUN ls /usr/bin/
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-12 30
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang-12 30
RUN rm /usr/bin/ld && ln -s /usr/bin/ld.lld /usr/bin/ld
